version: 1.36.0.{build}
os: Visual Studio 2017
clone_folder: C:\Projects\MaterialX

environment:
  matrix:
    - CMAKE_PLATFORM: "Visual Studio 14 2015"
      PYTHON: C:\Python26
      VS_PLATFORM: x86
      VS_COMPILER: vs2015
    - CMAKE_PLATFORM: "Visual Studio 14 2015 Win64"
      PYTHON: C:\Python27-x64
      VS_PLATFORM: x64
      VS_COMPILER: vs2015
    - CMAKE_PLATFORM: "Visual Studio 15 2017"
      PYTHON: C:\Python35
      VS_PLATFORM: x86
      VS_COMPILER: vs2017
    - CMAKE_PLATFORM: "Visual Studio 15 2017 Win64"
      PYTHON: C:\Python36-x64
      VS_PLATFORM: x64
      VS_COMPILER: vs2017

configuration:
  - Release

install:
  - set PATH=%PYTHON%;%PATH%

build_script:
  - mkdir build
  - cd build
  - cmake -DMATERIALX_BUILD_PYTHON=ON -DMATERIALX_WARNINGS_AS_ERRORS=ON -G "%CMAKE_PLATFORM%" ..
  - cmake --build . --target install --config %CONFIGURATION%
  - ctest --output-on-failure --build-config %CONFIGURATION%
  - cmake -E chdir ../python/MaterialXTest python main.py

after_build:
  - cd C:\Projects\MaterialX\build\installed
  - 7z a -r C:\Projects\MaterialX\MaterialX-Windows-%APPVEYOR_REPO_BRANCH%-%VS_PLATFORM%-%VS_COMPILER%-%APPVEYOR_BUILD_NUMBER%.zip .

artifacts:
- path: MaterialX-Windows-%APPVEYOR_REPO_BRANCH%-%VS_PLATFORM%-%VS_COMPILER%-%APPVEYOR_BUILD_NUMBER%.zip
  name: MaterialX_ADSK

deploy:
- provider: GitHub
  prerelease: true
  on:
    VS_PLATFORM: x64
    # branch: adsk_update_shadergen
  auth_token:
    secure: qg4BvNKremS4OMcbGZEjaXrumrQ+8/pJvr3WrNqM1ZQDyzvNpmUEA0ZMRkUJzeOh
