name: Create Branch and PR

on:
  workflow_dispatch:  # This allows for manual triggering.
  schedule:
    - cron: '0 0 * * 6'  # This sets the workflow to run every Saturday at midnight.

jobs:
  create-branch-and-pr:
    runs-on: ubuntu-latest
    env:
      MERGE_BRANCH: new-branch-${{ github.run_number }}  # Define the new branch name globally.


    steps:
    - name: Checkout main branch
      uses: actions/checkout@v2
      with:
        ref: main

    - name: Create new branch
      run: |
        git checkout -b $MERGE_BRANCH

    - name: Push new branch
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git push origin $MERGE_BRANCH

    - name: Create pull request to adsk_contrib/dev
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh pr create \
          --title "Merge $NEW_BRANCH into adsk_contrib/dev" \
          --body "Auto-created PR to merge $NEW_BRANCH into adsk_contrib/dev" \
          --head $NEW_BRANCH \
          --base adsk_contrib/dev \
          --reviewer "ehlenl"