void mx_sheen_brdf(float weight, color _color, float roughness, vector _normal, BSDF base, output BSDF result)
{
    // Top layer transmission to atttenuate base layer.
    // We use a LUT of directional albedo for this.
    //float albedo = mx_microfacet_sheen_albedo(NdotV, alpha);
    //float topTrans = clamp(1.0 - albedo, 0.0, 1.0);

	result = weight * _color * sheen(_normal, roughness) + (1.0 - weight) * base;
}
